<?php foreach ($publications as $publi): ?>
<article style="">
        <header>
        <h1><?php echo $publi->getTitle();?></h1>
        </header>
        <?php echo $publi->getContent();?>
        <footer>
                <p>
                    <small>
                        <time datetime="2011-12-10" pubdate>Publicado 10-12-2011</time>
                         - <a href="#" class="comment" id="<?php echo $publi->getId(); ?>">Comentar</a> - <a href="" class="done" id="<?php echo $publi->getId(); ?>">Comentarios</a> (<?php echo $comments = 0; ?>)
                    </small>
                </p>
        </footer>
     <div class="comment_done rounded" id="done<?php echo $publi->getId(); ?>" >
        <p>Listado de comentarios para este post</p>
    </div>
    <div class="comments rounded" id="coment<?php echo $publi->getId(); ?>" style="border: 1px solid #CCCCCC;">
        <form>
            <div class="send_comment"><input type="submit" class="rounded" value="Comentar" /></div>
            <span><label><span class="remark">*</span>Nonbre:</label><input type="text" class="name rounded" /></span> 
            <span><label><span class="remark">*</span>Email:</label><input type="text" class="email rounded" /></span>
            <textarea class="content rounded"></textarea>
        </form>
    </div>
    </article>
<?php endforeach; ?>