<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="robots" content="index,follow" />
        <meta name="description" content="Desarrollo web, programación con lenguajes web como PHP, Zend Framework 2, JavaScript, jQuery algo de estilo con CSS3, maquetando una web con HTML5">
        <meta name="keywords" content="ZendFramework 2, zf2, jQuery, JavaScript, html5, css3">
        <meta name="Author" content="Jose Manuel Orts, jortsc@gmail.com">
        <?php 
         echo $this->headTitle($this->translate('HayStack, a lot of things!'))->setSeparator(' - ')->setAutoEscape(false);
         echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ;
         echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon_rounded.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/style_f.css');
         echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                 ->prependFile($this->basePath() . '/js/jquery.js') 
              //echo $this->content; 
             //echo $this->url('home') 
             //echo $this->translate('All rights reserved.') 
         ?>
        <script type="text/javascript">
           jQuery(document).ready(function(){
               jQuery('#searcher').val('Buscar en HayStack. . .');
               jQuery('#searcher').click(function(){
                   if(jQuery('#searcher').val() == 'Buscar en HayStack. . .'){
                       jQuery('#searcher').val('');
                   }
               });
               jQuery('#searcher').blur(function(){
                    if(jQuery('#searcher').val() == ''){
                       jQuery('#searcher').val('Buscar en HayStack. . .');
                   }
               });
               /*Functions for examples*/
                jQuery("#testjq").click(function(){
                    jQuery('#result').load('resources/test.html');
                });
                jQuery("#testjq2").click(function(){
                    jQuery('#result2').load('resources/test.php #elemento',{user:'jQuery'}, function(respuesta, estado, XMLHttpRequest){
                       if(estado == 'error' ){
                           alert('Código: '+XMLHttpRequest.status+' Estado:'+XMLHttpRequest.statusText);
                       }
                       else{
                           alert('Código: '+XMLHttpRequest.status+' Estado: '+XMLHttpRequest.statusText);
                       }
                    });
                });
                
//                jQuery("#underconstruction").fadeIn('slow');                
//                setTimeout (hideUnder, 2000); 
//                function hideUnder(){
//                   jQuery('#underconstruction').fadeOut('slow');
//                }

                jQuery('.comment').click(function(evt){
                        evt.preventDefault();
                        var id = evt.target.id
                        jQuery('#coment'+id).slideToggle('slow');
                });
                
                jQuery('.done').click(function(evt){
                        evt.preventDefault();
                        var id = evt.target.id
                        jQuery('#done'+id).slideToggle('slow');
                });
           });
       </script>
    </head>
    <body>
<!--        <div id='underconstruction' class='rounded30'><div class="underimg"><img class="rounded30" src="<?php echo $this->basePath();?>/img/underconstruction.jpg"></div></div>-->

</body>
		<div id="container">
			<header id="header">
                            <a href="<?php echo $this->url('home');?>"><img style="width:235px;height:60px;" id="logo" src="<?php echo $this->basePath();?>/img/haystack_f.png" /></a>
			</header>
			<nav id="menu"  class="rounded">
                            <div>
				<ul class="nav">
					<li><a href="<?php echo $this->url('home');?>" class="rounded">Inicio</a></li>
					<li><a href="#" class="rounded">Autor</a></li>
					<li><a href="<?php echo $this->url('home'); ?>home/contact" class="rounded">Contacto</a></li>
				</ul>
                                <div class="search_cont">
                                    <form action="#" method="POST">
                                         <ul class="search">
                                                <li>
                                                        <input type="text" id="searcher" class="searchinput rounded" /> 
                                                        <input type="button" value="Buscar" id="searchsubmit" class="searchsubmit  rounded" />
                                                        <div class="clear"></div>
                                                </li>
                                        </ul>
                                    </form>
                                </div>
                                    <div class="clear"></div>
                           </div>
			</nav>
			<div class="content">
                             <section id="seccion">
                                 <?php echo $this->content;?>
                             </section>
                            <div class="col_left">
                                    <aside id="leftbar" class="rounded">
                                        <div class="about">
                                            <h3 class="about_title">Sobre <?php echo $this->author->getNombre();?></h3> 
                                            <img class="author_img rounded" src="<?php echo $this->basePath().$this->author->getImg();?>">
                                            <p>
                                                <?php echo $this->author->getDescription();?>
                                            </p>
                                            <div class="clear"></div>
                                       </div>
                                       <div class="about">
                                           <h3 class="about_title">Por secciones</h3>
                                           <div class="setcions">
                                               <ul>
                                                   <li><a href="#" class="rounded">Geek</a></li>
                                                   <li><a href="#" class="rounded">Zend Framework</a></li>
                                                   <li><a href="#" class="rounded">jQuery</a></li>
                                                   <li><a href="#" class="rounded">HTML5</a></li>
                                                   <li><a href="#" class="rounded">CSS3</a></li>
                                               </ul>
                                           </div>
                                       </div>
                                        <div class="about">
                                            <h3 class="about_title">Enlaces</h3>
                                            <ul>
                                                <li><a href="#">GitHub</a></li>
                                                <li><a href="#">Google+</a></li>
                                                <li><a href="#">LinkedIn</a></li>
                                           </ul>
                                     </div>
                                        <div class="about_title"></div>
                                        <figure class="logos">
                                            <a href="framework.zend.com/manual/2.0/en/index.html">
                                                <img class="img_medium rounded" src="<?php echo $this->basePath();?>/img/zf2.png" />
                                            </a>
                                                <figcaption></figcaption>
                                        </figure>
                                        <figure class="logos">
                                            <a href="http://jquery.com/">
                                                <img class="img_m rounded" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcScXNot80T4kN9DwUjuiCiV5ZV877yLd7bP7-VR75dcyNm8R1LWbQ" />
                                            </a>  
                                        </figure>

                                </aside>
                           </div>
                            <div class="clear"></div>
			</div>
			<footer id="foot" class="rounded">
                            <small id="footlegals">&copy;2012 My personal blog - Designed and performed by <span class="by">Jose Manuel Orts</span><span class="tech"> with <a href="http://framework.zend.com/manual/2.0/en/index.html" target="_blank">ZF2</a>, <a href="http://jquery.com/" target="_blank">jQuery</a>, <a href="http://dev.w3.org/html5/html-author/" target="_blank">HTML5</a> and <a href="http://css3clickchart.com/#box-sizing" target="_blank">CSS3</a></span></small>
			</footer>
		</div>
	</body>
</html>